[package]
name = 'core-packages/instance-of'
description = 'https://github.com/jsdotlua/luau-polyfill'
version = '1.2.3'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
