[package]
name = 'core-packages/luau-polyfill'
description = 'https://github.com/jsdotlua/luau-polyfill'
version = '1.2.3'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
Boolean = 'core-packages/boolean@1.2.3'
Collections = 'core-packages/collections@1.2.3'
Console = 'core-packages/console@1.2.3'
ES7Types = 'core-packages/es7-types@1.2.3'
InstanceOf = 'core-packages/instance-of@1.2.3'
Math = 'core-packages/math@1.2.3'
Number = 'core-packages/number@1.2.3'
String = 'core-packages/string@1.2.3'
Symbol = 'core-packages/symbol@1.0.0'
Timers = 'core-packages/timers@1.2.3'
